src_dir: /appl/src/
openssl_version: 1.1.1g
openssl_install_dir: /appl/openssl/
openssl_config_args: -fPIC -DPIC --prefix={{ openssl_install_dir }}
unixodbc_version: 2.3.7
unixodbc_install_dir: /appl/unixodbc/
unixodbc_config_args: --prefix={{ unixodbc_install_dir }}
cyrus_sasl_version: 2.1.27
cyrus_sasl_install_dir: /appl/cyrus_sasl/
cyrus_sasl_config_args: --prefix={{ cyrus_sasl_install_dir }} --with-plugindir=/appl/cyrus_sasl/lib/sasl2 --with-configdir=/appl/cyrus_sasl/lib/sasl2 --with-saslauthd=/appl/cyrus_sasl/var/run --with-ldap --disable-checkapop --disable-cram --disable-digest --disable-scram --disable-otp --disable-gssapi --disable-anon
openldap_version: 2.4.50
openldap_install_dir: /appl/openldap/
openldap_config_args: --prefix={{ openldap_install_dir }} --disable-bdb --disable-hdb --enable-ldap --enable-meta --enable-sql --enable-overlays --enable-spasswd --enable-modules --with-cyrus-sasl --with-tls=openssl
working_env:
  LD_LIBRARY_PATH: "{{ openssl_install_dir }}/lib:{{ cyrus_sasl_install_dir }}/lib:{{ unixodbc_install_dir }}/lib:{{ openldap_install_dir }}/lib:$LD_LIBRARY_PATH"
  CC: gcc
  CFLAGS: -O -g
  CPPFLAGS: -I{{ openssl_install_dir }}/include -I{{ unixodbc_install_dir }}/include -I{{ cyrus_sasl_install_dir }}/include -I{{ openldap_install_dir }}/include -I/usr/include -DF00=42
  LDFLAGS: -L{{ openssl_install_dir }}/lib -Wl,-rpath,{{ openssl_install_dir }}/lib -L{{ unixodbc_install_dir }}/lib -L{{ cyrus_sasl_install_dir }}/lib -L{{ openldap_install_dir }}/lib -L/usr/lib
  LIBS: -lpthread -ldl
  LDAP_HOME: "{{ openldap_install_dir }}"
