---
- import_tasks: copy_source.yml
  tags:
    - copy:source

- import_tasks: upgrade_unixodbc.yml
  tags:
    - upgrade:unixodbc

- import_tasks: upgrade_openssl.yml
  tags:
    - upgrade:openssl

- import_tasks: upgrade_openldap_1.yml
  tags:
    - upgrade:openldap:1

- import_tasks: upgrade_cyrussasl.yml
  tags:
    - upgrade:cyrussasl

- import_tasks: upgrade_openldap_2.yml
  tags:
    - upgrade:openldap:2
