- name: Upgrade OpenLDAP 1
  environment: "{{ working_env }}"
  shell: |
    echo "test"
  args:
    chdir: "{{ src_dir }}openldap-{{ openldap_version }}"
  register: result
  tags:
    - upgrade:openldap:2

- name: Print config output
  debug:
    msg: "{{ result.stdout_lines }}"
  tags:
    - never
    - debug
    - debug-upgrade:openldap:1

#make distclean
#./configure {{ openldap_config_args }}
#make depend
#make
#make install
